server:
  port: 8080

spring:
  application:
    name: medical-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: medical-user
          uri: lb://medical-user
          predicates:
            - Path=/api/auth/**, /api/users/**, /api/patients/**, /api/otp/**, /v3/api-docs/**
          filters:
            - StripPrefix=1
        - id: medical-appointment
          uri: lb://medical-appointment
          predicates:
            - Path=/api/appointment/**, /v3/api-docs/**
          filters:
            - StripPrefix=1
        - id: medical-notification
          uri: lb://medical-notification
          predicates:
            - Path=/api/notification/**, /v3/api-docs/**
          filters:
            - StripPrefix=1
  main:
    web-application-type: reactive

# Springdoc配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls-primary-name: medical-gateway
  api-docs:
    enabled: true
    path: /v3/api-docs

# Eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

# 日志配置
logging:
  level:
    com.medical.gateway: info
    org.springframework.cloud.gateway: info
    org.springframework.cloud.netflix.eureka: info

# Redis配置（用于限流）
data:
  redis:
    host: 123.60.186.10
    port: 6379
    password: hxp123
    database: 0

# Resilience4j断路器配置
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s
        cancelRunningFuture: true 