name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "master", "develop", "feature/*" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
    
    - name: Build with Maven
      run: |
        echo "Current directory: $(pwd)"
        echo "List directory contents:"
        ls -la
        echo "Building with Maven..."
        mvn clean package -DskipTests
    
    - name: List files in target directories
      run: |
        echo "Listing target directories..."
        ls -la */target/ || echo "No target directories found"
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: jars
        path: |
          **/target/*.jar
          !**/target/original-*.jar
          !**/target/*-sources.jar
          !**/target/*-javadoc.jar

  docker:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: jars
    
    - name: Display structure of downloaded files
      run: |
        echo "Current directory structure:"
        ls -R
    
    - name: Prepare artifacts for Docker
      run: |
        echo "Creating target directories..."
        mkdir -p medical-eureka-server/target
        mkdir -p medical-gateway/target
        mkdir -p medical-user/target
        echo "Moving jar files..."
        mv medical-eureka-server-1.0-SNAPSHOT.jar medical-eureka-server/target/ || echo "Eureka server jar not found"
        mv medical-gateway-1.0-SNAPSHOT.jar medical-gateway/target/ || echo "Gateway jar not found"
        mv medical-user-1.0-SNAPSHOT.jar medical-user/target/ || echo "User service jar not found"
        echo "Final directory structure:"
        ls -R
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Eureka Server
      uses: docker/build-push-action@v4
      with:
        context: ./medical-eureka-server
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/medical-eureka-server:latest
    
    - name: Build and push Gateway
      uses: docker/build-push-action@v4
      with:
        context: ./medical-gateway
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/medical-gateway:latest
    
    - name: Build and push User Service
      uses: docker/build-push-action@v4
      with:
        context: ./medical-user
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/medical-user:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Create .env file
      run: |
        echo "Creating .env file..."
        echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" > .env
        cat .env
    
    - name: Copy deployment files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "docker-compose.yml,.env"
        target: "/app/medical-platform"
    
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /app/medical-platform
          echo "Pulling new images..."
          docker-compose pull
          echo "Stopping old containers..."
          docker-compose down
          echo "Starting new containers..."
          docker-compose up -d
          echo "Cleaning up old images..."
          docker image prune -f
